from django.db import models
from django.contrib.auth.models import User
class Profile(models.Model):
    ROLE_CHOICES=[('SUPER_ADMIN','Super Admin'),('NATIONAL','National'),('REGIONAL','Régional'),('SUPERVISEUR','Superviseur'),('CONTROLEUR','Contrôleur')]
    user=models.OneToOneField(User,on_delete=models.CASCADE,related_name='profile'); role=models.CharField(max_length=20,choices=ROLE_CHOICES); region=models.CharField(max_length=120,blank=True); departement=models.CharField(max_length=120,blank=True); arrondissement=models.CharField(max_length=120,blank=True); brigade=models.CharField(max_length=120,blank=True); language=models.CharField(max_length=2,default='fr')
class Setting(models.Model): key=models.CharField(max_length=100,unique=True); value=models.JSONField(default=dict); updated_by=models.ForeignKey(User,null=True,blank=True,on_delete=models.SET_NULL); updated_at=models.DateTimeField(auto_now=True)
class Report(models.Model):
    STATUS=[('DRAFT','Brouillon'),('SUBMITTED','Soumis'),('TRANSMITTED','Transmis au national'),('VALIDATED','Validé'),('RETURNED','Renvoyé pour correction')]
    month=models.CharField(max_length=7); brigade=models.CharField(max_length=120); region=models.CharField(max_length=120); department=models.CharField(max_length=120,blank=True); arrondissement=models.CharField(max_length=120,blank=True); status=models.CharField(max_length=20,choices=STATUS,default='DRAFT'); deadline=models.DateField(null=True,blank=True); submitted_at=models.DateTimeField(null=True,blank=True); submitted_by=models.ForeignKey(User,null=True,blank=True,on_delete=models.SET_NULL); payload=models.JSONField(default=dict); national_edit_history=models.JSONField(default=list); created_at=models.DateTimeField(auto_now_add=True); updated_at=models.DateTimeField(auto_now=True)
class BowlDeclaration(models.Model):
    SANCTIONS=[('','Aucune'),('NIVEAU_1','Niveau 1 — Avertissement'),('NIVEAU_2','Niveau 2 — Mise en demeure'),('NIVEAU_3','Niveau 3 — Suspension')]
    QUOTA_STATUS=[('SOUS_QUOTA','Sous quota'),('A_SURVEILLER','À surveiller'),('QUOTA_ATTEINT','Quota atteint')]
    report=models.ForeignKey(Report,on_delete=models.CASCADE,related_name='bowls'); company_id=models.CharField(max_length=80); company_name=models.CharField(max_length=255); site_reference=models.CharField(max_length=120,blank=True); month=models.CharField(max_length=7); number=models.DecimalField(max_digits=12,decimal_places=2)
    gold_extracted_kg=models.DecimalField(max_digits=10,decimal_places=3,default=0); debt_adjustment_kg=models.DecimalField(max_digits=10,decimal_places=3,default=0); observation=models.TextField(blank=True)
    quota_kg=models.DecimalField(max_digits=10,decimal_places=3,default=0); realization_rate=models.DecimalField(max_digits=6,decimal_places=3,default=0); monthly_debt_kg=models.DecimalField(max_digits=10,decimal_places=3,default=0); cumulative_debt_kg=models.DecimalField(max_digits=10,decimal_places=3,default=0); sanction_level=models.CharField(max_length=20,choices=SANCTIONS,blank=True,default=''); quota_status=models.CharField(max_length=20,choices=QUOTA_STATUS,blank=True,default='')
    locked=models.BooleanField(default=False); declared_by=models.ForeignKey(User,null=True,blank=True,on_delete=models.SET_NULL); modified_by_national=models.ForeignKey(User,null=True,blank=True,on_delete=models.SET_NULL,related_name='bowl_modifications'); modification_reason=models.TextField(blank=True); history=models.JSONField(default=list)
class CorrectionRequest(models.Model):
    STATUS=[('PENDING','En attente'),('TREATED','Traitée'),('REJECTED','Rejetée')]
    bowl=models.ForeignKey(BowlDeclaration,on_delete=models.CASCADE,related_name='correction_requests'); requester=models.ForeignKey(User,on_delete=models.PROTECT); proposed_number=models.DecimalField(max_digits=12,decimal_places=2); reason=models.TextField(); status=models.CharField(max_length=20,choices=STATUS,default='PENDING'); treated_by=models.ForeignKey(User,null=True,blank=True,on_delete=models.SET_NULL,related_name='treated_requests'); treatment_reason=models.TextField(blank=True); created_at=models.DateTimeField(auto_now_add=True); treated_at=models.DateTimeField(null=True,blank=True)
class GeoRecord(models.Model):
    TYPE=[('SITE','Site'),('CONTROL','Contrôle'),('SENSIBILISATION','Sensibilisation'),('INCIDENT','Incident/Alerte')]
    type=models.CharField(max_length=20,choices=TYPE); reference=models.CharField(max_length=100); title=models.CharField(max_length=255); region=models.CharField(max_length=120,blank=True); department=models.CharField(max_length=120,blank=True); arrondissement=models.CharField(max_length=120,blank=True); latitude=models.DecimalField(max_digits=10,decimal_places=7); longitude=models.DecimalField(max_digits=10,decimal_places=7); accuracy_m=models.DecimalField(max_digits=10,decimal_places=2,null=True,blank=True); altitude=models.DecimalField(max_digits=10,decimal_places=2,null=True,blank=True); source_position=models.CharField(max_length=30,default='GPS auto'); captured_at=models.DateTimeField(); created_by=models.ForeignKey(User,on_delete=models.PROTECT); status=models.CharField(max_length=50,blank=True); metadata=models.JSONField(default=dict); created_at=models.DateTimeField(auto_now_add=True)
class AuditLog(models.Model):
    actor=models.ForeignKey(User,null=True,blank=True,on_delete=models.SET_NULL); action=models.CharField(max_length=120); entity=models.CharField(max_length=120); entity_id=models.CharField(max_length=120,blank=True); before=models.JSONField(null=True,blank=True); after=models.JSONField(null=True,blank=True); reason=models.TextField(blank=True); ip=models.GenericIPAddressField(null=True,blank=True); created_at=models.DateTimeField(auto_now_add=True)
    class Meta: ordering=['-created_at']
class DataRecord(models.Model):
    MODULES=[('SOCIETES','Sociétés'),('SITES','Sites'),('PRODUCTION','Production'),('ACTEURS','Acteurs'),('CONTROLES','Contrôles'),('SENSIBILISATION','Sensibilisation'),('FLUX','Flux'),('RESSOURCES','Ressources'),('DIFFICULTES','Difficultés'),('ACTIONS','Actions'),('ALERTES','Alertes')]
    module=models.CharField(max_length=30,choices=MODULES); region=models.CharField(max_length=120,blank=True); department=models.CharField(max_length=120,blank=True); arrondissement=models.CharField(max_length=120,blank=True); brigade=models.CharField(max_length=120,blank=True); month=models.CharField(max_length=7,blank=True); data=models.JSONField(default=dict); created_by=models.ForeignKey(User,on_delete=models.PROTECT); updated_at=models.DateTimeField(auto_now=True); created_at=models.DateTimeField(auto_now_add=True)
