from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True
    dependencies=[('auth','0012_alter_user_first_name_max_length')]
    operations=[
      migrations.CreateModel(name='Profile',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('role',models.CharField(choices=[('SUPER_ADMIN','Super Admin'),('NATIONAL','National'),('REGIONAL','Régional'),('SUPERVISEUR','Superviseur'),('CONTROLEUR','Contrôleur')],max_length=20)),('region',models.CharField(blank=True,max_length=120)),('departement',models.CharField(blank=True,max_length=120)),('arrondissement',models.CharField(blank=True,max_length=120)),('brigade',models.CharField(blank=True,max_length=120)),('language',models.CharField(default='fr',max_length=2)),('user',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='profile',to='auth.user'))]),
      migrations.CreateModel(name='Setting',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('key',models.CharField(max_length=100,unique=True)),('value',models.JSONField(default=dict)),('updated_at',models.DateTimeField(auto_now=True)),('updated_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='auth.user'))]),
      migrations.CreateModel(name='Report',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('month',models.CharField(max_length=7)),('brigade',models.CharField(max_length=120)),('region',models.CharField(max_length=120)),('department',models.CharField(blank=True,max_length=120)),('arrondissement',models.CharField(blank=True,max_length=120)),('status',models.CharField(choices=[('DRAFT','Brouillon'),('SUBMITTED','Soumis'),('TRANSMITTED','Transmis au national'),('VALIDATED','Validé'),('RETURNED','Renvoyé pour correction')],default='DRAFT',max_length=20)),('deadline',models.DateField(blank=True,null=True)),('submitted_at',models.DateTimeField(blank=True,null=True)),('payload',models.JSONField(default=dict)),('national_edit_history',models.JSONField(default=list)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('submitted_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='auth.user'))]),
      migrations.CreateModel(name='AuditLog',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('action',models.CharField(max_length=120)),('entity',models.CharField(max_length=120)),('entity_id',models.CharField(blank=True,max_length=120)),('before',models.JSONField(blank=True,null=True)),('after',models.JSONField(blank=True,null=True)),('reason',models.TextField(blank=True)),('ip',models.GenericIPAddressField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('actor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='auth.user'))]),
      migrations.CreateModel(name='DataRecord',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('module',models.CharField(choices=[('SOCIETES','Sociétés'),('SITES','Sites'),('PRODUCTION','Production'),('ACTEURS','Acteurs'),('CONTROLES','Contrôles'),('SENSIBILISATION','Sensibilisation'),('FLUX','Flux'),('RESSOURCES','Ressources'),('DIFFICULTES','Difficultés'),('ACTIONS','Actions'),('ALERTES','Alertes')],max_length=30)),('region',models.CharField(blank=True,max_length=120)),('department',models.CharField(blank=True,max_length=120)),('arrondissement',models.CharField(blank=True,max_length=120)),('brigade',models.CharField(blank=True,max_length=120)),('month',models.CharField(blank=True,max_length=7)),('data',models.JSONField(default=dict)),('updated_at',models.DateTimeField(auto_now=True)),('created_at',models.DateTimeField(auto_now_add=True)),('created_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='auth.user'))]),
      migrations.CreateModel(name='GeoRecord',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('type',models.CharField(choices=[('SITE','Site'),('CONTROL','Contrôle'),('SENSIBILISATION','Sensibilisation'),('INCIDENT','Incident/Alerte')],max_length=20)),('reference',models.CharField(max_length=100)),('title',models.CharField(max_length=255)),('region',models.CharField(blank=True,max_length=120)),('department',models.CharField(blank=True,max_length=120)),('arrondissement',models.CharField(blank=True,max_length=120)),('latitude',models.DecimalField(decimal_places=7,max_digits=10)),('longitude',models.DecimalField(decimal_places=7,max_digits=10)),('accuracy_m',models.DecimalField(blank=True,decimal_places=2,max_digits=10,null=True)),('altitude',models.DecimalField(blank=True,decimal_places=2,max_digits=10,null=True)),('source_position',models.CharField(default='GPS auto',max_length=30)),('captured_at',models.DateTimeField()),('status',models.CharField(blank=True,max_length=50)),('metadata',models.JSONField(default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('created_by',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='auth.user'))]),
      migrations.CreateModel(name='BowlDeclaration',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('company_id',models.CharField(max_length=80)),('company_name',models.CharField(max_length=255)),('month',models.CharField(max_length=7)),('number',models.DecimalField(decimal_places=2,max_digits=12)),('locked',models.BooleanField(default=False)),('modification_reason',models.TextField(blank=True)),('history',models.JSONField(default=list)),('declared_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='auth.user')),('modified_by_national',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='bowl_modifications',to='auth.user')),('report',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='bowls',to='app.report'))]),
      migrations.CreateModel(name='CorrectionRequest',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('proposed_number',models.DecimalField(decimal_places=2,max_digits=12)),('reason',models.TextField()),('status',models.CharField(choices=[('PENDING','En attente'),('TREATED','Traitée'),('REJECTED','Rejetée')],default='PENDING',max_length=20)),('treatment_reason',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('treated_at',models.DateTimeField(blank=True,null=True)),('bowl',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='correction_requests',to='app.bowldeclaration')),('requester',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to='auth.user')),('treated_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='treated_requests',to='auth.user'))]),
    ]
