# Generated by Django 5.2.6 on 2026-09-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='bowldeclaration',
            name='cumulative_debt_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bowldeclaration',
            name='debt_adjustment_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bowldeclaration',
            name='gold_extracted_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bowldeclaration',
            name='monthly_debt_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bowldeclaration',
            name='observation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bowldeclaration',
            name='quota_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bowldeclaration',
            name='quota_status',
            field=models.CharField(blank=True, choices=[('SOUS_QUOTA', 'Sous quota'), ('A_SURVEILLER', 'À surveiller'), ('QUOTA_ATTEINT', 'Quota atteint')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bowldeclaration',
            name='realization_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='bowldeclaration',
            name='sanction_level',
            field=models.CharField(blank=True, choices=[('', 'Aucune'), ('NIVEAU_1', 'Niveau 1 — Avertissement'), ('NIVEAU_2', 'Niveau 2 — Mise en demeure'), ('NIVEAU_3', 'Niveau 3 — Suspension')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bowldeclaration',
            name='site_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
